Repository ZeRiix/projet-git-3iW, pull requests merged in 2023-02, with the labels that each got.

#16 [ADD]: Adding ConnexionPage.vue close #1
  src/views/ConnexionPage.vue
  src/views/Tab1Page.vue
  src/views/Tab2Page.vue
  src/views/Tab3Page.vue
  src/views/TabsPage.vue
Labels: feature

#17 [ADD]: InscriptionPage.vue Resolved #2
  src/views/InscriptionPage.vue
Labels: feature

#18 [ADD] : Adding control on password input - InscriptionPage.vue
  .vscode/extensions.json
  package-lock.json
  src/views/InscriptionPage.vue
Labels: feature

#19 Feature/show unshow text on input password Close #4
  .gitignore
  src/views/ConnexionPage.vue
  src/views/InscriptionPage.vue
Labels: feature

#20 Feature/home page Close#5
  src/views/HomePage.vue
Labels: feature

#21 Déploiement de l'application sur le serveur de production
  .browserslistrc
  .eslintrc.js
  .gitignore
  babel.config.js
  capacitor.config.ts
  cypress.json
  ionic.config.json
  jest.config.js
  package.json
  public/assets/icon/favicon.png
  public/assets/icon/icon.png
  public/assets/shapes.svg
  public/index.html
  src/App.vue
  src/components/ExploreContainer.vue
  src/main.ts
  src/router/index.ts
  src/shims-vue.d.ts
  src/theme/variables.css
  src/views/ConnexionPage.vue
  src/views/HomePage.vue
  src/views/InscriptionPage.vue
  tests/e2e/.eslintrc.js
  tests/e2e/plugins/index.js
  tests/e2e/specs/test.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
  tests/unit/example.spec.ts
  tsconfig.json
Labels: deploy

#22 [ADD]: Adding EventPage.vue Close #6
  src/views/EventsPage.vue
Labels: feature

#23 [ADD] : Adding join action on event clicked Close#7
  src/views/EventsPage.vue
Labels: feature

#24 [ADD]: Adding function on join input in eventPage to make a transaction Close#8
  src/views/EventsPage.vue
Labels: feature

#25 Feature/panel admin page Close#9
  src/views/PanelAdminPage.vue
Labels: feature

#26 Feature/add likes or comments on events Close #10
  src/views/EventsPage.vue
Labels: feature

#27 Déploiement de l'application sur le serveur de production
  src/views/EventsPage.vue
  src/views/PanelAdminPage.vue
Labels: deploy

#29 [ADD]: Adding AdminComments.vue Close #12
  src/views/AdminComments.vue
Labels: feature

#30 Déploiement de l'application sur le serveur de production
  src/views/AdminComments.vue
Labels: deploy

#31 [FIX] : Fix admin connexion now WORKING for prod Close #13
  src/views/PanelAdminPage.vue
Labels: bug

#34 Feature/responsive mobile Close #15
  src/views/HomePage.vue
Labels: feature

#37 [ADD]: navbar component responsive
  src/components/NavbarComponent.vue
Labels: feature

#38 [ADD]: Adding readme & license
  LICENSE
  README.md
Labels: feature

#39 [ADD]: Adding responsive mobile on App
  src/views/HomePage.vue
Labels: feature

#42 [ADD]: Adding merge request template
  .github/MERGE_REQUEST_TEMPLATE/merge_request_template.md
Labels: feature

#43 Déploiement de l'application sur le serveur de production
  .github/MERGE_REQUEST_TEMPLATE/merge_request_template.md
  LICENSE
  README.md
  src/components/NavbarComponent.vue
  src/views/HomePage.vue
Labels: deploy
